services:
  tests:
    image: api_tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/workspace
    env_file:
      - .env
    environment:
      STAGE: ${STAGE}
      THREADS: ${THREADS:-3}
      MARKER: ${MARKER:-all}
    command: /bin/sh -c "pytest -sv -o log_cli=true -n=$$THREADS -m=$$MARKER --alluredir=allure-results"
    tty: true

  report:
    image: api_tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/workspace
    command: /bin/sh -c "ls -la && allure generate allure-results --clean -o allure-report"
    working_dir: /usr/workspace
