name: API tests
run-name: Test ${{ github.event.inputs.ENV }} | ${{ github.event.inputs.MARKER }} marker | ${{ github.event.inputs.THREADS }} treads

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: "Environment"
        required: true
        type: environment
        default: "cloud_dev"

      MARKER:
        description: "Select pytest marker"
        required: true
        default: "smoke"
        type: choice
        options:
          - smoke
          - regression

      THREADS:
        description: "Select threads count"
        required: false
        default: "1"
        type: choice
        options:
          - 1
          - 3
          - 5

jobs:
  api-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      # Подготовка environment.properties
      - name: Prepare Allure environment
        run: |
          mkdir -p allure-results
          echo "Branch=${{ github.ref_name }}" > allure-results/environment.properties
          echo "Commit=${{ github.sha }}" >> allure-results/environment.properties
          echo "Environment=${{ github.event.inputs.ENV }}" >> allure-results/environment.properties

      - name: Create .env file with credentials only
        run: |
          cat > .env << EOF
          ENV=${{ github.event.inputs.ENV }}
          DEV_LOGIN=${{ secrets.DEV_LOGIN }}
          DEV_PASSWORD=${{ secrets.DEV_PASSWORD }}
          DEV_CLIENT_ID=${{ secrets.DEV_CLIENT_ID }}
          CLOUD_LOGIN=${{ secrets.CLOUD_LOGIN }}
          CLOUD_PASSWORD=${{ secrets.CLOUD_PASSWORD }}
          CLOUD_CLIENT_ID=${{ secrets.CLOUD_CLIENT_ID }}
          STAGE_LOGIN=${{ secrets.STAGE_LOGIN }}
          STAGE_PASSWORD=${{ secrets.STAGE_PASSWORD }}
          STAGE_CLIENT_ID=${{ secrets.STAGE_CLIENT_ID }}
          EOF

      # Запуск тестов (скорее всего нужно добавить переменные логин и пароль)
      - name: Run API tests via docker
        env:
          STAGE: ${{ secrets.STAGE }}
          MARKER: ${{ github.event.inputs.MARKER }}
          THREADS: ${{ github.event.inputs.THREADS }}
        run: |
          docker compose up tests --build --exit-code-from tests

      # Шаг 4 - Копирование истории
      - name: Copy Allure history
        run: |
          mkdir -p allure-results/history
          if [ -d "./.github/gh-pages/history" ]; then
            cp -R ./.github/gh-pages/history/* allure-results/history/
          fi

      # Шаг 5 - Генерация отчета
      - name: Generate Allure-report
        env:
          STAGE: ${{ secrets.STAGE }}
        run: |
          docker compose up report --build

      # Шаг 6 - Деплой на gh-pages
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: false